# Generated by Django 3.2.7 on 2021-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20211011_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, verbose_name="UUID"
            ),
        ),
    ]
