version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: 'staticfiles-mysite-nginx'
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  
  web:
    build: .
    container_name: 'mysite'
    volumes:
      - .:/app
