# Generated by Django 3.2.7 on 2021-10-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, verbose_name="UUID"
            ),
        ),
    ]
