# Generated by Django 3.2.7 on 2021-10-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_auto_20211011_1703"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="option_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="text",
        ),
    ]
